version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: smarthack
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sudo
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
    networks:
      - mynetwork
  backend:
    image: iolah/smarthack-be-2020:latest
    depends_on:
      - database
    restart: always
    ports:
      - "2020:2020"
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
